import { Inter } from "next/font/google";
import "../global.scss";
import Header from "../components/header";
import Footer from "../components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Head içeriğini buraya ekleyebilirsiniz */}
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={`${inter.className} d-flex flex-column justify-content-between vh-100`}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
